flowchart TD
  load_modules[1.Load modules]
  create[2.Create]
  activate[3.Activate]
  install_libraries[4.Install Python libraries]
  check[5.Check installed Python libraries]
  use[6.Use]
  deactivate[7.Deactivate]

  load_modules --> create
  create --> activate
  activate --> install_libraries
  install_libraries --> check
  check --> use
  use --> deactivate
  deactivate --> activate
