  graph TB

  Node1 -- interactive --> SubGraph2Flow
  Node1 -- sbatch --> SubGraph2Flow
  SubGraph2Flow(calculation nodes) 


        Terminal/ThinLinc -- usr --> Node1
        
        subgraph "Kebnekaise"
        end
