flowchart TD

  subgraph R
    say_hello[3.2.Say hello print]
    see_installed_packages[3.3.See installed packages installed.packages]
    load_package[3.4.Load a package library]
  end
  run_r_script[4.Run an R script Rscript]

  run_r_script --> say_hello
  run_r_script --> see_installed_packages
  run_r_script --> load_package

