flowchart TD

  subgraph R
    say_hello[4.2.Say hello]
    see_installed_packages[See installed packages]
    load_package[Load a package]
  end
  run_r_script[4.Run an R script Rscript]

  run_r_script --> say_hello
  run_r_script --> see_installed_packages
  run_r_script --> load_package

